app.version=3.0
logging.level.org.springframework.security=INFO
spring.web.error.path=/generalError
spring.servlet.multipart.max-file-size=50GB
spring.servlet.multipart.max-request-size=50GB
spring.thymeleaf.cache=false
spring.session.jdbc.initialize-schema=never
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.id.new_generator_mappings=true
